config/routes.rb
Rails.application.routes.draw do
  resources :players
  resources :lineups do
    resources :players, only: [:index, :new]
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get '/users/show', to: 'users#show'
  root to: "lineups#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]
  has_many :lineups
  has_many :players, through: :lineups

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @lineups = @user.lineups
    @this_weeks_lineups = @lineups.this_weeks_lineups
  end
end

app/views/users/show.html.erb
<p class="col-sm-10 row">
  <strong class="col-sm-4 row">Email Address: </strong>
  <%= @user.email %>
</p>

<p class="col-sm-10 row">
  <strong class="col-sm-4 row">Most Used Player(s): </strong>
  <%= @user.lineups.most_used_player %>
</p>

<p class="col-sm-10 row">
  <strong class="col-sm-4 row">Lineups Created This Week:</strong>
  <br>
  <% @this_weeks_lineups.each do |lineup| %>
    <%= link_to lineup.name, lineup_path(lineup.id) %>
    <br>
  <% end %>
</p>

<button onclick="showLineups()" type="button" class="btn btn-primary">Show all lineups</button>
<div id="lineups"></div>