config/routes.rb
Rails.application.routes.draw do
  resources :players
  resources :lineups do
    resources :players, only: [:index, :new]
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get '/users/show', to: 'users#show'
  root to: "lineups#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/lineup.rb
class Lineup < ApplicationRecord
  validates :name, presence: true

  belongs_to :user
  has_many :lineups_players
  has_many :players, through: :lineups_players
  accepts_nested_attributes_for :players
  scope :this_weeks_lineups, -> { where("DATE(created_at) > ?", (Date.today).to_time - 7.days) }

  def players_attributes=(player_attributes)
    player_attributes.values.each do |player_attribute|
      player = Player.find(player_attribute)
      if !self.players.include?(player)
        self.players << player
      end
    end
  end

  def self.most_used_player
    max = 0
    most_used = ''
    Player.all.each do |player|
      if player.lineups.length > max
        max = player.lineups.length
        most_used = player.name
      elsif player.lineups.length == max
        most_used = most_used + ' ' + player.name
      end
    end
    return most_used
  end

  def total_points
    points = 0
      self.players.each do |player|
        if player.actualPoints != nil
          points += player.actualPoints
        end
      end
    points
  end

end

app/controllers/lineups_controller.rb
class LineupsController < ApplicationController
  before_action :set_lineup, only: [:show, :edit, :update, :destroy]

  # GET /lineups
  # GET /lineups.json
  def index
    authenticate_user!
    @lineups = Lineup.where(user_id: current_user.id)
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @lineups}
    end
  end

  # GET /lineups/1
  # GET /lineups/1.json
  def show
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @lineup}
    end
  end

  # GET /lineups/new
  def new
    @lineup = Lineup.new
  end

  # GET /lineups/1/edit
  def edit
  end

  # POST /lineups
  # POST /lineups.json
  def create
    authenticate_user!
    @lineup = current_user.lineups.build(lineup_params)
    respond_to do |format|
      if @lineup.save
        format.html { redirect_to @lineup, notice: 'Lineup was successfully created.' }
        format.json { render :show, status: :created, location: @lineup }
      else
        format.html { render :new }
        format.json { render json: @lineup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lineups/1
  # PATCH/PUT /lineups/1.json
  def update
    if @lineup.user_id == current_user.id
      respond_to do |format|
        if @lineup.update(lineup_params)
          format.html { redirect_to @lineup, notice: 'Lineup was successfully updated.' }
          format.json { render :show, status: :ok, location: @lineup }
        else
          format.html { render :edit }
          format.json { render json: @lineup.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to @lineup, notice: 'Sorry, you cannot edit a lineup you did not create.' }
        format.json { head :no_content }
      end
    end
  end

  # DELETE /lineups/1
  # DELETE /lineups/1.json
  def destroy
    if @lineup.user_id == current_user.id
      @lineup.destroy
      respond_to do |format|
        format.html { redirect_to lineups_url, notice: 'Lineup was successfully deleted.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to lineups_url, notice: 'You cannot destroy a lineup you did not create.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lineup
      @lineup = Lineup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lineup_params
      params.require(:lineup).permit(:name, :description, player_ids:[], players_attributes: [:player_id, :quarterback, :runningback1, :runningback2, :widereciever1, :widereciever2, :widereciever3, :tightend, :flex, :defense])
    end
end

app/helpers/lineups_helper.rb
module LineupsHelper
end

app/views/lineups/_form.html.erb
<%= form_with(model: lineup, local: true) do |form| %>
  <% if lineup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lineup.errors.count, "error") %> prohibited this lineup from being saved:</h2>

      <ul>
      <% lineup.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <label for="lineup_name" class="col-sm-2 col-form-label">Name</label>
    <div class="col-sm-10">
      <%= form.text_field :name, id: :lineup_name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <label for="lineup_description" class="col-sm-2 col-form-label">Description</label>
    <div class="col-sm-10">
      <%= form.text_field :description, id: :lineup_description, class: 'form-control' %>
    </div>
  </div>

  <well>
    <div class="form-group row">
      <label class="col-sm-2 col-form-label"> Quarterback </label>
      <div class="col-sm-10">
        <%= form.collection_select 'players_attributes[quarterback]', Player.where(position: 'Quarterback'), :id, :name, {}, class: 'form-control' %>
      </div>
    </div>
  </well>

    <div class="form-group row">
      <label class="col-sm-2 col-form-label"> Runningback 1 </label>
      <div class="col-sm-10">
        <%= form.collection_select 'players_attributes[runningback1]', Player.where(position: 'Runningback1'), :id, :name, {}, class: 'form-control'  %>
      </div>
    </div>

    <div class="form-group row">
      <label class="col-sm-2 col-form-label"> Runningback 2 </label>
      <div class="col-sm-10">
        <%= form.collection_select 'players_attributes[runningback2]', Player.where(position: 'Runningback2'), :id, :name, {}, class: 'form-control'  %>
      </div>
    </div>

    <div class="form-group row">
      <label class="col-sm-2 col-form-label"> Widereceiver 1 </label>
      <div class="col-sm-10">
        <%= form.collection_select 'players_attributes[widereciever1]', Player.where(position: 'Widereciever1'), :id, :name, {}, class: 'form-control'  %>
      </div>
    </div>

    <div class="form-group row">
      <label class="col-sm-2 col-form-label"> Widereceiver 2 </label>
      <div class="col-sm-10">
        <%= form.collection_select 'players_attributes[widereciever2]', Player.where(position: 'Widereciever2'), :id, :name, {}, class: 'form-control'  %>
      </div>
    </div>

    <div class="form-group row">
      <label class="col-sm-2 col-form-label"> Widereceiver 3 </label>
      <div class="col-sm-10">
        <%= form.collection_select 'players_attributes[widereciever3]', Player.where(position: 'Widereciever3'), :id, :name, {}, class: 'form-control'  %>
      </div>
    </div>

    <div class="form-group row">
      <label class="col-sm-2 col-form-label"> Tightend </label>
      <div class="col-sm-10">
        <%= form.collection_select 'players_attributes[tightend]', Player.where(position: 'Tightend'), :id, :name, {}, class: 'form-control'  %>
      </div>
    </div>

    <div class="form-group row">
      <label class="col-sm-2 col-form-label"> Flex </label>
      <div class="col-sm-10">
        <%= form.collection_select 'players_attributes[flex]', Player.where(position: 'Flex'), :id, :name, {}, class: 'form-control'  %>
      </div>
    </div>

    <div class="form-group row">
      <label class="col-sm-2 col-form-label"> Defense: </label>
      <div class="col-sm-10">
        <%= form.collection_select 'players_attributes[defense]', Player.where(position: 'Defense'), :id, :name, {}, class: 'form-control'  %>
      </div>
    </div>

  <div class="actions">
    <button type="submit" class="btn btn-primary">Create Lineup</button>
  </div>
<% end %>

app/views/lineups/edit.html.erb
<h1>Editing Lineup</h1>

<%= render 'form', lineup: @lineup %>

<%= link_to 'Back', lineups_path %>

app/views/lineups/index.html.erb
<h1>Lineups</h1>

<table class="table" id="myTable">
  <thead>
    <tr>
      <th onclick="sortTable(0)" scope="col">Name</th>
      <th onclick="sortTable(1)" scope="col">Description</th>
      <th onclick="sortTable(2)" scope="col">Total Points</th>
      <th onclick="sortTable(3)" scope="col">Players</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lineups.each do |lineup| %>
      <tr>
        <td><%= link_to lineup.name, lineup %></td>
        <td><%= lineup.description %></td>
        <td><%= lineup.total_points %></td>
        <td><% lineup.players.each do |player| %>
            <%= player.name %>
            <br>
        <% end %>
        </td>
        <% if lineup.user_id == current_user.id %>
          <%# <td><%= link_to 'Edit', edit_lineup_path(lineup) %> <%# </td> %>
          <td><%= link_to 'Delete', lineup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/lineups/new.html.erb
<h1>New Lineup</h1>

<%= render 'form', lineup: @lineup %>

app/views/lineups/show.html.erb
   <button id="previous" data-id="<%= @lineup.id %>" onclick="previousLineup()" type="button" class="btn btn-primary">Show Previous Lineup</button>
   <button id="next" data-id="<%= @lineup.id %>" onclick="nextLineup()" type="button" class="btn btn-primary">Show Next Lineup</button>
  <br></br>

<p class="col-sm-10 row">
  <div id="name"><strong class="col-sm-4">Name:</strong> <%= @lineup.name %></div>
</p>

<p class="col-sm-10 row">
  <div id="description"><strong class="col-sm-4">Description:</strong><%= @lineup.description %></div>
</p>

<p class="col-sm-10 row">
  <div id="total_points"><strong class="col-sm-2">Total Points: </strong> <%= @lineup.total_points %></div>
</p>

  <table class="table" id="myTable">
    <thead>
      <tr>
        <th onclick="sortTable(0)" scope="col">Name</th>
        <th onclick="sortTable(1)" scope="col">Position</th>
        <th onclick="sortTable(2)" scope="col">Projected Points</th>
        <th onclick="sortTable(3)" scope="col">Actual Points</th>
        <th onclick="sortTable(4)" scope="col">Point Differential</th>
        <th onclick="sortTable(5)" scope="col">Status</th>
        <th colspan="1"></th>
      </tr>
    </thead>

    <tbody id="tableBody">
  <% @lineup.players.each do |player| %>
    <tr>
      <td><%= player.name %></td>
      <td><%= player.position %></td>
      <td><%= player.projectedPoints %></td>
      <td><%= player.actualPoints %></td>
      <td><%= player.point_differential %></td>
      <td><%= LineupsPlayer.find_by(player_id: player.id, lineup_id: @lineup.id).player_starting %></td>
    </tr>
      <% end %>
    </tbody>
  </table>

  <% if @lineup.user_id == current_user.id %>
    <br>
    <%# <%= link_to 'Edit Lineup', edit_lineup_path(@lineup) %>
  <% end %>

<script>

$(function () {
  $('form').submit(function(event) {
    event.preventDefault();

    const form = this;
    const values = $(form).serialize();

    $.ajaxSetup({
      headers: {
        'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
      }
    });

    $.post('/players.json', values)
      .done(({ data }) => {
        const player = new Player (data.attributes.name, data.attributes.position, data['attributes']['actual-points'], data['attributes']['projected-points'], "Starting");
        $("#myTable tbody").append(player.render())
        form.reset();
      });
  });
});

function Player(name, position, actualPoints, projectedPoints, status) {
  this.name = name;
  this.position = position;
  if (actualPoints != null) {
    this.actualPoints = actualPoints;
  } else {
    this.actualPoints = '';
  }
  if (projectedPoints != null) {
    this.projectedPoints = projectedPoints;
  } else {
    this.projectedPoints = '';
  }
  this.status = status;
}

Player.prototype.pointDifferential = function() {
  if (this.projectedPoints != '' && this .actualPoints != ''){
    return this.projectedPoints - this.actualPoints;
  } else {
    return '';
  }
}

Player.prototype.render = function() {
  return (`
    <tr class="child">
      <td>${this.name}</td>
      <td>${this.position}</td>
      <td>${this.actualPoints}</td>
      <td>${this.projectedPoints}</td>
      <td>${this.pointDifferential()}</td>
      <td>${this.status}</td>
    </tr>
  `);
}
</script>