config/routes.rb
Rails.application.routes.draw do
  resources :players
  resources :lineups do
    resources :players, only: [:index, :new]
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get '/users/show', to: 'users#show'
  root to: "lineups#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/player.rb
class Player < ApplicationRecord
  validates :name, presence: true
  validates :position, presence: true

  has_many :lineups_players
  has_many :lineups, through: :lineups_players

  accepts_nested_attributes_for :lineups

  def lineups_players_attributes=(lineups_player_attributes)
    lineups_player_attributes.values.each do |lineups_player_attribute|
      if LineupsPlayer.find_by(lineup_id: lineups_player_attribute[:lineup_id], player_id: self.id)
        LineupsPlayer.find_by(lineup_id: lineups_player_attribute[:lineup_id], player_id: self.id).update(player_starting: lineups_player_attribute[:player_starting])
      end
    end
  end

  def point_differential
    if self.actualPoints != nil && self.projectedPoints != nil
      return self.actualPoints - self.projectedPoints
    else
      return ''
    end
  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players or GET lineups/id:/players if linking from a lineup show page.
  # GET /players.json
  def index
    if params[:lineup_id]
      @players = Lineup.find(params[:lineup_id]).players
      @lineup = Lineup.find(params[:lineup_id])
    else
      @players = Player.all
    end
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @players}
    end
  end

  # GET /players/1
  # GET /players/1.json
  def show
    @lineups_players = LineupsPlayer.where(player_id: @player.id)
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @player}
    end
  end

  # GET /players/new or GET lineups/id:/players/new if linking from a lineup show page.
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    authenticate_user!
    @player = Player.new(player_params)
    #Useful for performance in large applications versus .create.

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render json: @player, status: 201}
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    authenticate_user!
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    authenticate_user!
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:name, :position, :projectedPoints, :actualPoints, :salary, lineup_ids:[], lineups_players_attributes: [:player_starting, :lineup_id, :id])
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_with(model: player, local: true) do |form| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<h1>Players</h1>

<table class="table" id="myTable">
  <thead>
    <tr>
      <th onclick="sortTable(0)">Name</th>
      <th onclick="sortTable(1)">Position</th>
      <th onclick="sortTable(2)">Salary</th>
      <th onclick="sortTable(3)">Projected Points</th>
      <th onclick="sortTable(4)">Actual Points</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.name %></td>
        <td><%= player.position %></td>
        <td><%= player.salary %></td>
        <td><%= player.projectedPoints %></td>
        <td><%= player.actualPoints %></td>
        <td><%= link_to 'Show', player %></td>
        <% if @lineup != nil %>
          <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p class="col-sm-10 row">
  <strong class="col-sm-3 row">Name:</strong>
  <%= @player.name %>
</p>

<p class="col-sm-10 row">
  <strong class="col-sm-3 row">Position:</strong>
  <%= @player.position %>
</p>

<p class="col-sm-10 row">
  <strong class="col-sm-3 row">Salary:</strong>
  <%= @player.salary %>
</p>

<p class="col-sm-10 row">
  <strong class="col-sm-3 row">Projected Points:</strong>
  <%= @player.projectedPoints %>
</p>

<p class="col-sm-10 row">
  <strong class="col-sm-3 row">Actual Points:</strong>
  <%= @player.actualPoints %>
</p>

<p class="col-sm-10 row">
  <strong class="col-sm-3 row">Lineups:</strong>
  <br>
  <% @player.lineups.each do |lineup| %>
    <% if lineup.user_id == current_user.id %>
      <%= lineup.name %>
      <br>
      Player Notes: <%= @lineups_players.find_by(lineup_id: lineup.id).player_starting %>
      <br>
    <% end %>
  <% end %>
</p>

<%= link_to 'Back', players_path %>